default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: 12345678
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: point_management

test:
  <<: *default
  database: hotel-management-app_test

production:
  <<: *default
  database: hotel-management-app_production
  username: hotel-management-app
  password: <%= ENV['MANAGELIBRARY_DATABASE_PASSWORD'] %>
